[package]
name = "kinemagic"
version = "0.1.0"
edition = "2024"
description = "A simple CLI for modeling and solving multibody mechanisms."

authors = ["Jens Olschewski"]

[[bin]]
name = "km"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.5", features = ["derive"] }
nalgebra = "0.35"
serde = { version = "1", features = ["derive"] }
serde_yaml_ng = "0.10"
thiserror = "2.0.20"
