Output docs/assets/viewer.gif

Set FontSize 14
Set FontFamily "JetBrains Mono"
Set Width 900
Set Height 450
Set Padding 30
Set TypingSpeed 50ms

Type "km solve examples/spherical_three_body_chain.yaml --view"
Enter
Set TypingSpeed 0ms
Type "++l"
Sleep 5
Type "q"
Set TypingSpeed 50ms
Type "km solve examples/spherical_plate_3d_motion.yaml --view"
Enter
Set TypingSpeed 0ms
Type "4++l"
Sleep 5
Type "q"
